### ISSUE TITLE
Failure due to lack of pycapnp

### ISSUE THREAD

**Issue by vitaly-krugl** [numenta/nupic.regression#49]
https://travis-ci.org/numenta/nupic.regression/builds/151840034

```
Running script-run-examples.sh...

Traceback (most recent call last):
  File "/home/travis/build/numenta/nupic.regression/nupic/examples/bindings/sparse_matrix_how_to.py", line 31, in <module>
    from nupic.bindings.math import *
  File "/home/travis/.local/lib/python2.7/site-packages/nupic/bindings/math.py", line 42, in <module>
    _nupic_bindings_load_capnp_shared_object()
  File "/home/travis/.local/lib/python2.7/site-packages/nupic/bindings/math.py", line 38, in _nupic_bindings_load_capnp_shared_object
    capnpPackageDir = imp.find_module('capnp')[1]
ImportError: No module named capnp
```

**Comment by vitaly-krugl** [comment]
The latest nupic.bindings require pycapnp on Linux and OS X (but not on Windows). This is a transient situation in nupic.core's integraion of capnproto that will eventually get resolved in a cleaner way across platforms. For now, we'll add `pip install pycapnp==0.5.8` in this repo's `.travis.yml`.
